apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: monlat-agent
  namespace: default
  labels:
    app: monlat-agent
spec:
  selector:
    matchLabels:
      app: monlat-agent
  template:
    metadata:
      labels:
        app: monlat-agent
    spec:
      serviceAccount: monlat
      containers:
      - name: monlat-agent
        image: docker.io/bonavadeur/monlat-agent:v2
