apiVersion: v1
kind: Service
metadata:
  name: monlat
  labels:
    app: monlat
spec:
  type: ClusterIP
  selector:
    app: monlat
  ports:
  - name: http-metrics
    port: 9090
    targetPort: 9090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monlat
  namespace: default
  labels:
    app: monlat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monlat
  template:
    metadata:
      labels:
        app: monlat
    spec:
      serviceAccount: monlat
      hostname: monlat
      containers:
      - name: monlat
        image: docker.io/bonavadeur/monlat:v2
        imagePullPolicy: Always
        ports:
        - containerPort: 9090
          name: http-metrics
        readinessProbe:
          httpGet:
            path: /healthz
            port: 9090
          initialDelaySeconds: 20
          periodSeconds: 10
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - node1
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: monlat
  name: monlat
  namespace: default
spec:
  endpoints:
  - honorLabels: true
    interval: 5s
    path: /metrics
    port: http-metrics
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app: monlat
---
